name: theory_creator
description: Creates a theory document for each argument
publish_to: none
version: 1.0.0
environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  parser:
    path: ../parser
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  test: ^1.20.2
  very_good_analysis: ^2.4.0
