#!/usr/bin/env python3
"""
Swift to Spanish Exercise Translator
Translates all Swift exercises from English to Spanish.
"""

import os
import json
import re
from pathlib import Path
from typing import Dict, List

# Common translations
TRANSLATIONS = {
    # General terms
    "Calculate": "Calcula",
    "the sum": "la suma",
    "the difference": "la diferencia",
    "the product": "el producto",
    "the quotient": "el cociente",
    "the remainder": "el resto",
    "between": "entre",
    "then print": "luego imprime",
    "print": "imprime",
    "variable": "variable",
    "Complete the code": "Completa el codigo",
    "in order to": "para",
    "create": "crear",
    "What is the": "Cual es el",
    "output": "salida",
    "Which output produces": "Que salida produce",
    "the following code": "el siguiente codigo",
    "from": "de",
    "to": "a",
    "Multiply": "Multiplica",
    "per": "por",
    "Subtract": "Resta",
    "Add": "Anade",
    "Remove": "Elimina",
    "Insert": "Inserta",
    "Get": "Obtén",
    "Use": "Usa",
    "Declare": "Declara",
    "Define": "Define",
    "Return": "Devuelve",
    "Call": "Llama",
    "Make": "Haz",
    "Write": "Escribe",
    "Create": "Crea",

    # Variable names
    "sum": "suma",
    "difference": "diferencia",
    "product": "producto",
    "quotient": "cociente",
    "remainder": "resto",
    "result": "resultado",
    "count": "conteo",
    "total": "total",
    "value": "valor",
    "name": "nombre",
    "index": "indice",
    "length": "longitud",
    "size": "tamano",
    "item": "elemento",
    "items": "elementos",
    "element": "elemento",
    "elements": "elementos",
    "array": "arreglo",
    "number": "numero",
    "numbers": "numeros",
    "numbers": "numeros",
    "string": "cadena",
    "strings": "cadenas",
    "text": "texto",
    "character": "caracter",
    "characters": "caracteres",
    "boolean": "booleano",
    "bool": "bool",
    "true": "verdadero",
    "false": "falso",
    "list": "lista",
    "lists": "listas",
    "dictionary": "diccionario",
    "dictionaries": "diccionarios",
    "set": "conjunto",
    "tuple": "tupla",
    "function": "funcion",
    "functions": "funciones",
    "method": "metodo",
    "methods": "metodos",
    "class": "clase",
    "classes": "clases",
    "object": "objeto",
    "objects": "objetos",
    "instance": "instancia",
    "parameter": "parametro",
    "parameters": "parametros",
    "argument": "argumento",
    "arguments": "argumentos",
    "return": "retorno",
    "loop": "bucle",
    "loops": "bucles",
    "condition": "condicion",
    "conditions": "condiciones",
    "statement": "sentencia",
    "statements": "sentencias",
    "expression": "expresion",
    "expressions": "expresiones",
    "operator": "operador",
    "operators": "operadores",
    "operation": "operacion",
    "operations": "operaciones",
    "type": "tipo",
    "types": "tipos",
    "constant": "constante",
    "constants": "constantes",
    "keyword": "palabra clave",
    "keywords": "palabras clave",
    "comment": "comentario",
    "comments": "comentarios",
    "code": "codigo",
    "program": "programa",
    "programs": "programas",
    "script": "guion",
    "scripts": "guiones",
    "file": "archivo",
    "files": "archivos",
    "path": "ruta",
    "folder": "carpeta",
    "directory": "directorio",
    "message": "mensaje",
    "messages": "mensajes",
    "error": "error",
    "errors": "errores",
    "warning": "advertencia",
    "warnings": "advertencias",
    "exception": "excepcion",
    "exceptions": "excepciones",
    "data": "datos",
    "information": "informacion",
    "input": "entrada",
    "inputs": "entradas",
    "output": "salida",
    "outputs": "salidas",
    "user": "usuario",
    "users": "usuarios",
    "system": "sistema",
    "application": "aplicacion",
    "applications": "aplicaciones",
    "interface": "interfaz",
    "interfaces": "interfaces",
    "implementation": "implementacion",
    "implementations": "implementaciones",
    "definition": "definicion",
    "definitions": "definiciones",
    "declaration": "declaracion",
    "declarations": "declaraciones",
    "assignment": "asignacion",
    "assignments": "asignaciones",
    "comparison": "comparacion",
    "comparisons": "comparaciones",
    "equality": "igualdad",
    "inequality": "desigualdad",
    "greater": "mayor",
    "less": "menor",
    "equal": "igual",
    "not equal": "no igual",
    "greater than": "mayor que",
    "less than": "menor que",
    "greater than or equal": "mayor o igual que",
    "less than or equal": "menor o igual que",
    "and": "y",
    "or": "o",
    "not": "no",
    "if": "si",
    "else": "sino",
    "else if": "sino si",
    "switch": "cambiar",
    "case": "caso",
    "break": "romper",
    "continue": "continuar",
    "for": "para",
    "while": "mientras",
    "do": "hacer",
    "in": "en",
    "range": "rango",
    "step": "paso",
    "each": "cada",
    "iterate": "iterar",
    "iteration": "iteracion",
    "iterations": "iteraciones",
    "collection": "coleccion",
    "collections": "colecciones",
    "sequence": "secuencia",
    "sequences": "secuencias",
    "first": "primero",
    "last": "ultimo",
    "second": "segundo",
    "third": "tercero",
    "next": "siguiente",
    "previous": "anterior",
    "current": "actual",
    "initial": "inicial",
    "final": "final",
    "start": "inicio",
    "end": "fin",
    "begin": "comenzar",
    "finish": "terminar",
    "complete": "completar",
    "incomplete": "incompleto",
    "empty": "vacio",
    "full": "lleno",
    "contains": "contiene",
    "includes": "incluye",
    "excludes": "excluye",
    "find": "encontrar",
    "search": "buscar",
    "replace": "reemplazar",
    "update": "actualizar",
    "delete": "eliminar",
    "insert": "insertar",
    "append": "agregar",
    "prepend": " anteponer",
    "remove": "eliminar",
    "add": "anadir",
    "subtract": "restar",
    "multiply": "multiplicar",
    "divide": "dividir",
    "modulo": "modulo",
    "power": "potencia",
    "square": "cuadrado",
    "cube": "cubo",
    "root": "raiz",
    "absolute": "absoluto",
    "minimum": "minimo",
    "maximum": "maximo",
    "average": "promedio",
    "mean": "media",
    "median": "mediana",
    "mode": "moda",
    "sum": "suma",
    "total": "total",
    "count": "conteo",
    "length": "longitud",
    "width": "ancho",
    "height": "alto",
    "depth": "profundidad",
    "area": "area",
    "volume": "volumen",
    "perimeter": "perimetro",
    "circumference": "circunferencia",
    "radius": "radio",
    "diameter": "diametro",
    "angle": "angulo",
    "degree": "grado",
    "radian": "radian",
    "coordinate": "coordenada",
    "coordinates": "coordenadas",
    "point": "punto",
    "points": "puntos",
    "line": "linea",
    "lines": "lineas",
    "shape": "forma",
    "shapes": "formas",
    "circle": "circulo",
    "square": "cuadrado",
    "rectangle": "rectangulo",
    "triangle": "triangulo",
    "polygon": "poligono",
    "color": "color",
    "colors": "colores",
    "red": "rojo",
    "green": "verde",
    "blue": "azul",
    "yellow": "amarillo",
    "orange": "naranja",
    "purple": "morado",
    "pink": "rosa",
    "black": "negro",
    "white": "blanco",
    "gray": "gris",
    "grey": "gris",
    "brown": "marron",
    "transparent": "transparente",
    "opaque": "opaco",
    "visible": "visible",
    "hidden": "oculto",
    "show": "mostrar",
    "hide": "ocultar",
    "display": "mostrar",
    "render": "renderizar",
    "draw": "dibujar",
    "paint": "pintar",
    "fill": "llenar",
    "clear": "limpiar",
    "reset": "restablecer",
    "refresh": "actualizar",
    "reload": "recargar",
    "load": "cargar",
    "save": "guardar",
    "open": "abrir",
    "close": "cerrar",
    "exit": "salir",
    "quit": "salir",
    "cancel": "cancelar",
    "confirm": "confirmar",
    "accept": "aceptar",
    "reject": "rechazar",
    "allow": "permitir",
    "deny": "negar",
    "grant": "conceder",
    "revoke": "revocar",
    "permission": "permiso",
    "permissions": "permisos",
    "access": "acceso",
    "role": "rol",
    "roles": "roles",
    "user": "usuario",
    "users": "usuarios",
    "group": "grupo",
    "groups": "grupos",
    "team": "equipo",
    "teams": "equipos",
    "member": "miembro",
    "members": "miembros",
    "leader": "lider",
    "owner": "propietario",
    "admin": "administrador",
    "administrator": "administrador",
    "guest": "invitado",
    "visitor": "visitante",
    "anonymous": "anonimo",
    "public": "publico",
    "private": "privado",
    "protected": "protegido",
    "internal": "interno",
    "external": "externo",
    "local": "local",
    "global": "global",
    "static": "estatico",
    "dynamic": "dinamico",
    "constant": "constante",
    "variable": "variable",
    "readonly": "solo lectura",
    "writeonly": "solo escritura",
    "readwrite": "lectura escritura",
    "mutable": "mutable",
    "immutable": "inmutable",
    "reference": "referencia",
    "pointer": "puntero",
    "address": "direccion",
    "memory": "memoria",
    "stack": "pila",
    "heap": "monticulo",
    "queue": "cola",
    "stack": "pila",
    "tree": "arbol",
    "graph": "grafo",
    "node": "nodo",
    "nodes": "nodos",
    "edge": "arista",
    "edges": "aristas",
    "vertex": "vertice",
    "vertices": "vertices",
    "root": "raiz",
    "branch": "rama",
    "branches": "ramas",
    "leaf": "hoja",
    "leaves": "hojas",
    "parent": "padre",
    "child": "hijo",
    "children": "hijos",
    "sibling": "hermano",
    "siblings": "hermanos",
    "ancestor": "ancestro",
    "ancestors": "ancestros",
    "descendant": "descendiente",
    "descendants": "descendientes",
    "path": "ruta",
    "route": "ruta",
    "journey": "recorrido",
    "distance": "distancia",
    "shortest": "mas corto",
    "longest": "mas largo",
    "fastest": "mas rapido",
    "slowest": "mas lento",
    "optimal": "optimo",
    "best": "mejor",
    "worst": "peor",
    "good": "bueno",
    "bad": "malo",
    "better": "mejor",
    "worse": "peor",
    "right": "correcto",
    "wrong": "incorrecto",
    "correct": "correcto",
    "incorrect": "incorrecto",
    "true": "verdadero",
    "false": "falso",
    "yes": "si",
    "no": "no",
    "maybe": "quizas",
    "always": "siempre",
    "never": "nunca",
    "sometimes": "a veces",
    "often": "frecuentemente",
    "rarely": "rara vez",
    "usually": "generalmente",
    "normally": "normalmente",
    "typically": "tipicamente",
    "commonly": "comunmente",
    "frequently": "frecuentemente",
    "occasionally": "ocasionalmente",
    "periodically": "periodicamente",
    "regularly": "regularmente",
    "continuously": "continuamente",
    "constantly": "constantemente",
    "forever": "para siempre",
    "eternal": "eterno",
    "temporary": "temporal",
    "permanent": "permanente",
    "transient": "transitorio",
    "persistent": "persistente",
    "volatile": "volatil",
    "stable": "estable",
    "unstable": "inestable",
    "reliable": "confiable",
    "unreliable": "poco confiable",
    "available": "disponible",
    "unavailable": "no disponible",
    "ready": "listo",
    "not ready": "no listo",
    "pending": "pendiente",
    "processing": "procesando",
    "completed": "completado",
    "failed": "fallido",
    "success": "exito",
    "failure": "fallo",
    "error": "error",
    "warning": "advertencia",
    "info": "informacion",
    "debug": "depuracion",
    "trace": "rastreo",
    "log": "registro",
    "logs": "registros",
    "message": "mensaje",
    "messages": "mensajes",
    "notification": "notificacion",
    "notifications": "notificaciones",
    "alert": "alerta",
    "alerts": "alertas",
    "reminder": "recordatorio",
    "reminders": "recordatorios",
    "task": "tarea",
    "tasks": "tareas",
    "job": "trabajo",
    "jobs": "trabajos",
    "process": "proceso",
    "processes": "procesos",
    "thread": "hilo",
    "threads": "hilos",
    "fiber": "fibra",
    "fibers": "fibras",
    "routine": "rutina",
    "routines": "rutinas",
    "procedure": "procedimiento",
    "procedures": "procedimientos",
    "subroutine": "subrutina",
    "subroutines": "subrutinas",
    "function": "funcion",
    "functions": "funciones",
    "method": "metodo",
    "methods": "metodos",
    "constructor": "constructor",
    "constructors": "constructores",
    "destructor": "destructor",
    "destructors": "destructores",
    "initializer": "inicializador",
    "initializers": "inicializadores",
    "finalizer": "finalizador",
    "finalizers": "finalizadores",
    "getter": "obtenedor",
    "getters": "obtenedores",
    "setter": "establecedor",
    "setters": "establecedores",
    "property": "propiedad",
    "properties": "propiedades",
    "field": "campo",
    "fields": "campos",
    "attribute": "atributo",
    "attributes": "atributos",
    "member": "miembro",
    "members": "miembros",
    "namespace": "espacio de nombres",
    "namespaces": "espacios de nombres",
    "module": "modulo",
    "modules": "modulos",
    "package": "paquete",
    "packages": "paquetes",
    "library": "biblioteca",
    "libraries": "bibliotecas",
    "framework": "marco de trabajo",
    "frameworks": "marcos de trabajo",
    "dependency": "dependencia",
    "dependencies": "dependencias",
    "import": "importar",
    "export": "exportar",
    "require": "requerir",
    "include": "incluir",
    "exclude": "excluir",
    "inherit": "heredar",
    "override": "sobrescribir",
    "overload": "sobrecargar",
    "implement": "implementar",
    "extends": "extiende",
    "super": "super",
    "base": "base",
    "derived": "derivado",
    "abstract": "abstracto",
    "virtual": "virtual",
    "interface": "interfaz",
    "interfaces": "interfaces",
    "protocol": "protocolo",
    "protocols": "protocolos",
    "delegate": "delegado",
    "delegates": "delegados",
    "event": "evento",
    "events": "eventos",
    "handler": "manejador",
    "handlers": "manejadores",
    "callback": "retro llamada",
    "callbacks": "retro llamadas",
    "promise": "promesa",
    "promises": "promesas",
    "future": "futuro",
    "futures": "futuros",
    "async": "asincrono",
    "await": "esperar",
    "sync": "sincrono",
    "parallel": "paralelo",
    "serial": "serial",
    "concurrent": "concurrente",
    "sequential": "secuencial",
    "synchronous": "sincrono",
    "asynchronous": "asincrono",
    "blocking": "bloqueante",
    "nonblocking": "no bloqueante",
    "timeout": "tiempo de espera",
    "deadline": "fecha limite",
    "interval": "intervalo",
    "delay": "retraso",
    "duration": "duracion",
    "timestamp": "marca de tiempo",
    "date": "fecha",
    "time": "hora",
    "datetime": "fecha hora",
    "timezone": "zona horaria",
    "offset": "desplazamiento",
    "era": "era",
    "year": "ano",
    "month": "mes",
    "week": "semana",
    "day": "dia",
    "hour": "hora",
    "minute": "minuto",
    "second": "segundo",
    "millisecond": "milisegundo",
    "microsecond": "microsegundo",
    "nanosecond": "nanosegundo",
    "today": "hoy",
    "tomorrow": "manana",
    "yesterday": "ayer",
    "now": "ahora",
    "later": "despues",
    "sooner": "antes",
    "early": "temprano",
    "late": "tarde",
    "ago": "hace",
    "until": "hasta",
    "since": "desde",
    "during": "durante",
    "within": "dentro de",
    "before": "antes de",
    "after": "despues de",
    "at": "a las",
    "on": "el",
    "in": "en",
    "by": "por",
    "with": "con",
    "without": "sin",
    "through": "a traves de",
    "from": "de",
    "to": "a",
    "towards": "hacia",
    "away from": "lejos de",
    "into": "en",
    "onto": "sobre",
    "over": "sobre",
    "under": "debajo de",
    "above": "encima de",
    "below": "debajo de",
    "between": "entre",
    "among": "entre",
    "around": "alrededor de",
    "behind": "detras de",
    "in front of": "delante de",
    "next to": "al lado de",
    "near": "cerca de",
    "far from": "lejos de",
    "inside": "dentro de",
    "outside": "fuera de",
    "upon": "sobre",
    "across": "a traves de",
    "along": "a lo largo de",
    "against": "contra",
    "towards": "hacia",
    "via": "via",
    "per": "por",
    "plus": "mas",
    "minus": "menos",
    "times": "por",
    "divided by": "dividido por",
    "equals": "igual",
    "not equals": "no igual",
    "greater than": "mayor que",
    "less than": "menor que",
    "much": "mucho",
    "many": "muchos",
    "few": "pocos",
    "little": "poco",
    "some": "algunos",
    "any": "alguna",
    "all": "todos",
    "none": "ninguno",
    "both": "ambos",
    "either": "cualquiera",
    "neither": "ninguno de los dos",
    "each": "cada",
    "every": "cada",
    "other": "otro",
    "another": "otro",
    "same": "mismo",
    "different": "diferente",
    "similar": "similar",
    "identical": "identico",
    "equal": "igual",
    "equivalent": "equivalente",
    "corresponding": "correspondiente",
    "related": "relacionado",
    "unrelated": "no relacionado",
    "associated": "asociado",
    "connected": "conectado",
    "disconnected": "desconectado",
    "linked": "vinculado",
    "unlinked": "desvinculado",
    "bound": "vinculado",
    "unbound": "no vinculado",
    "free": "libre",
    "busy": "ocupado",
    "idle": "inactivo",
    "active": "activo",
    "inactive": "inactivo",
    "enabled": "habilitado",
    "disabled": "deshabilitado",
    "on": "encendido",
    "off": "apagado",
    "open": "abierto",
    "closed": "cerrado",
    "locked": "bloqueado",
    "unlocked": "desbloqueado",
    "checked": "marcado",
    "unchecked": "desmarcado",
    "selected": "seleccionado",
    "unselected": "no seleccionado",
    "focused": "enfocado",
    "blurred": "desenfocado",
    "hovered": "sobrevolado",
    "pressed": "presionado",
    "released": "liberado",
    "clicked": "clicado",
    "double clicked": "doble clic",
    "right clicked": "clic derecho",
    "dragged": "arrastrado",
    "dropped": "soltado",
    "scrolled": "desplazado",
    "resized": "redimensionado",
    "moved": "movido",
    "copied": "copiado",
    "cut": "cortado",
    "pasted": "pegado",
    "deleted": "eliminado",
    "inserted": "insertado",
    "updated": "actualizado",
    "created": "creado",
    "destroyed": "destruido",
    "modified": "modificado",
    "changed": "cambiado",
    "edited": "editado",
    "saved": "guardado",
    "loaded": "cargado",
    "refreshed": "actualizado",
    "reset": "restablecer",
    "cleared": "limpiado",
    "initialized": "inicializado",
    "finalized": "finalizado",
    "configured": "configurado",
    "setup": "configurar",
    "teardown": "desmontar",
    "installed": "instalado",
    "uninstalled": "desinstalado",
    "deployed": "desplegado",
    "undeployed": "no desplegado",
    "built": "construido",
    "rebuilt": "reconstruido",
    "compiled": "compilado",
    "interpreted": "interpretado",
    "executed": "ejecutado",
    "run": "ejecutar",
    "running": "ejecutando",
    "stopped": "detenido",
    "paused": "pausado",
    "resumed": "reanudado",
    "cancelled": "cancelado",
    "aborted": "abortado",
    "terminated": "terminado",
    "killed": "matado",
    "forked": "bifurcado",
    "spawned": "generado",
    "merged": "fusionado",
    "branched": "ramificado",
    "tagged": "etiquetado",
    "released": "lanzado",
    "published": "publicado",
    "subscribed": "suscrito",
    "unsubscribed": "desuscrito",
    "notified": "notificado",
    " messaged": "mensajado",
    "emailed": "enviado por correo",
    "called": "llamado",
    "answered": "respondido",
    "replied": "respondido",
    "forwarded": "reenviado",
    "redirected": "redirigido",
    "routed": "enrutado",
    "handled": "manejado",
    "processed": "procesado",
    "transformed": "transformado",
    "converted": "convertido",
    "encoded": "codificado",
    "decoded": "decodificado",
    "encrypted": "cifrado",
    "decrypted": "descifrado",
    "hashed": "hasheado",
    "signed": "firmado",
    "verified": "verificado",
    "validated": "validado",
    "authenticated": "autenticado",
    "authorized": "autorizado",
    "permission": "permiso",
    "forbidden": "prohibido",
    "allowed": "permitido",
    "denied": "denegado",
    "granted": "concedido",
    "revoked": "revocado",
}

def translate_text(text: str) -> str:
    """Translate English text to Spanish with smart variable name translation."""
    if not text or not text.strip():
        return text

    result = text
    # Apply translations in order of specificity (longer phrases first)
    for en, es in sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True):
        # Word boundary matching for better accuracy
        pattern = r'\b' + re.escape(en) + r'\b'
        result = re.sub(pattern, es, result, flags=re.IGNORECASE)

    return result

def translate_code_line(line: str) -> str:
    """Translate a line of code, preserving structure."""
    # Don't translate lines that are mostly syntax
    if any(marker in line for marker in ['import ', '#include', 'using ', 'package ', 'func ', 'def ', 'class ', 'struct ', 'enum ', 'var ', 'let ']):
        # Still translate comments in these lines
        if '#' in line:
            parts = line.split('#', 1)
            if len(parts) == 2:
                code_part = parts[0]
                comment_part = parts[1]
                translated_comment = translate_text(comment_part)
                return f"{code_part}# {translated_comment}"
        return line

    return line

def translate_exercise(content: str) -> str:
    """Translate an exercise file from English to Spanish."""
    lines = content.split('\n')
    result = []
    in_code_block = False
    in_solution = False
    in_answers = False
    code_block_indent = 0

    for line in lines:
        # Check for section tags
        if line.strip().startswith('# --'):
            result.append(line)
            in_solution = '--solutions--' in line
            in_answers = '--answers--' in line
            continue

        # Track code blocks
        if line.strip().startswith('```'):
            in_code_block = not in_code_block
            result.append(line)
            continue

        # Handle different sections
        if in_code_block:
            # Translate variable names and comments in code
            translated_line = line
            # Translate comments
            if '#' in line and '//' not in line:
                parts = line.split('#', 1)
                if len(parts) == 2:
                    code_part = parts[0]
                    comment = parts[1]
                    translated_line = f"{code_part}# {translate_text(comment).strip()}"
            # Translate inline comments with //
            if '//' in line:
                parts = line.split('//', 1)
                if len(parts) == 2:
                    code_part = parts[0]
                    comment = parts[1]
                    translated_line = f"{code_part}// {translate_text(comment).strip()}"

            # Translate variable names in solutions
            if in_solution:
                for en, es in [
                    ('sum', 'suma'),
                    ('difference', 'diferencia'),
                    ('product', 'producto'),
                    ('quotient', 'cociente'),
                    ('remainder', 'resto'),
                    ('result', 'resultado'),
                    ('count', 'conteo'),
                    ('total', 'total'),
                    ('value', 'valor'),
                    ('name', 'nombre'),
                    ('numbers', 'numeros'),
                    ('number', 'numero'),
                    ('array', 'arreglo'),
                    ('text', 'texto'),
                    ('output', 'salida'),
                    ('message', 'mensaje'),
                    ('length', 'longitud'),
                    ('size', 'tamano'),
                    ('index', 'indice'),
                    ('item', 'elemento'),
                    ('items', 'elementos'),
                ]:
                    # Only translate if it's a whole word (variable name)
                    translated_line = re.sub(r'\b' + en + r'\b', es, translated_line)

            result.append(translated_line)
        elif in_answers:
            # Translate answer options but preserve formatting
            result.append(translate_text(line))
        else:
            # Translate descriptions and instructions
            result.append(translate_text(line))

    return '\n'.join(result)

def translate_data_json(data: dict) -> dict:
    """Translate data.json content."""
    result = {}
    for key, value in data.items():
        if isinstance(value, dict):
            result[key] = {
                'order': value.get('order'),
                'title': translate_text(value.get('title', '')),
                'description': translate_text(value.get('description', '')),
            }
        else:
            result[key] = value
    return result

def main():
    """Main translation function."""
    base_path = Path('/Users/ale/github/codigo-questions')
    source_dir = base_path / 'en' / 'swift'
    target_dir = base_path / 'es' / 'swift'

    # Count files
    md_files = list(source_dir.rglob('*.md'))
    json_files = list(source_dir.rglob('data.json'))

    print(f"Found {len(md_files)} markdown files and {len(json_files)} JSON files to translate")

    translated_count = 0

    for source_file in source_dir.rglob('*'):
        if source_file.is_dir():
            continue

        # Calculate relative path
        rel_path = source_file.relative_to(source_dir)
        target_file = target_dir / rel_path

        # Create target directory
        target_file.parent.mkdir(parents=True, exist_ok=True)

        if source_file.name == 'data.json':
            # Translate JSON
            with open(source_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            translated_data = translate_data_json(data)
            with open(target_file, 'w', encoding='utf-8') as f:
                json.dump(translated_data, f, ensure_ascii=False, indent=2)
            print(f"Translated: {rel_path}")
            translated_count += 1

        elif source_file.suffix == '.md' and not source_file.name.startswith('_'):
            # Translate markdown exercise
            with open(source_file, 'r', encoding='utf-8') as f:
                content = f.read()

            translated_content = translate_exercise(content)

            with open(target_file, 'w', encoding='utf-8') as f:
                f.write(translated_content)

            print(f"Translated: {rel_path}")
            translated_count += 1

    print(f"\nTranslation complete! Translated {translated_count} files.")

if __name__ == '__main__':
    main()
