# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:very_good_analysis/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    implicit-casts: false
    implicit-dynamic: false
