name: json_creator
description: A simple command-line application.
publish_to: none
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  collection: ^1.17.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  json_sorter: ^1.0.0
  parser:
    path: ../parser
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0
