name: json_creator
description: A simple command-line application.
publish_to: none
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  json_sorter: ^1.0.0
  parser:
    path: ../parser
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  test: ^1.17.11
  very_good_analysis: ^2.3.0
