name: validator
description: Validates the questions.
version: 1.0.1
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  diff_match_patch: ^0.4.1
  parser:
    path: ../parser
  path: ^1.8.0
  trotter: ^2.0.0-dev.1

dev_dependencies:
  test: ^1.17.11
  very_good_analysis: ^2.3.0
