name: validator
description: Validates the questions.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  parser:
    path: ../parser
  path: ^1.8.0

dev_dependencies:
  test: ^1.17.11
  very_good_analysis: ^2.3.0
