name: cli
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  args: ^2.3.0
  colorize: ^3.0.0
  clippy:
    git:
      url: git@github.com:nank1ro/clippy.git
      ref: 1.0.1
  parser:
    path: ../parser

dev_dependencies:
  lints: ^1.0.0
