name: parser
description: The codigo questions parser.
version: 0.0.3
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  front_matter:
    git:
      url: https://github.com/nank1ro/front-matter
  json_annotation: ^4.8.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
