name: parser
description: The codigo questions parser.
version: 0.0.3
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  front_matter:
    git:
      url: https://github.com/nank1ro/front-matter
  json_annotation: ^4.5.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0
