name: parser
description: The codigo questions parser.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed: ^0.14.5
  front_matter:
    git:
      url: git://github.com/nank1ro/front-matter.git
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.1
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.0
  test: ^1.17.11
  very_good_analysis: ^2.3.0
