name: parser
description: The codigo questions parser.
version: 0.0.3
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  front_matter:
    git:
      url: git://github.com/nank1ro/front-matter.git
  json_annotation: ^4.4.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.1
  freezed: ^1.1.0
  json_serializable: ^6.1.4
  test: ^1.17.11
  very_good_analysis: ^2.3.0
