name: Deploy to Firebase Storage

on:
  push:
    branches:
      - main
    paths:
      - "curriculum.json"
      - "en/**"
      - "it/**"
      - "assets/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: upload-en
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: en
          destination: ${{ secrets.BUCKET_NAME }}

      - id: upload-it
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: it
          destination: ${{ secrets.BUCKET_NAME }}

      - id: upload-curriculum
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: curriculum.json
          destination: ${{ secrets.BUCKET_NAME }}

      - id: upload-assets
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: assets
          destination: ${{ secrets.BUCKET_NAME }}
