name: Deploy to Firebase Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - id: upload-en
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: en
          destination: ${{ secrets.BUCKET_NAME }}

      - id: upload-it
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: it
          destination: ${{ secrets.BUCKET_NAME }}
